"""uses table

Revision ID: 1f04d504d348
Revises: 79c97818e7e5
Create Date: 2021-04-11 01:42:59.457748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f04d504d348'
down_revision = '79c97818e7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('bitcoin_value', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('cash_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cash_balance')
    op.drop_column('user', 'bitcoin_value')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
