"""empty message

Revision ID: 617beb51bf87
Revises: e29c488ffd7c
Create Date: 2021-04-11 16:38:00.079319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617beb51bf87'
down_revision = 'e29c488ffd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_transaction_username'), 'transaction', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_username'), table_name='transaction')
    op.drop_column('transaction', 'username')
    # ### end Alembic commands ###
