"""empty message

Revision ID: 759d435602c8
Revises: bf69dd77c2de
Create Date: 2021-04-11 18:00:34.471470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759d435602c8'
down_revision = 'bf69dd77c2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('action', sa.String(length=16), nullable=True))
    op.add_column('transaction', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('order', sa.String(length=16), nullable=True))
    op.add_column('transaction', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('status', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'status')
    op.drop_column('transaction', 'price')
    op.drop_column('transaction', 'order')
    op.drop_column('transaction', 'amount')
    op.drop_column('transaction', 'action')
    # ### end Alembic commands ###
