"""empty message

Revision ID: bf69dd77c2de
Revises: 617beb51bf87
Create Date: 2021-04-11 16:50:35.026177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf69dd77c2de'
down_revision = '617beb51bf87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_username', table_name='transaction')
    op.create_index(op.f('ix_transaction_username'), 'transaction', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_username'), table_name='transaction')
    op.create_index('ix_transaction_username', 'transaction', ['username'], unique=1)
    # ### end Alembic commands ###
