"""transaction and product and strategy tables

Revision ID: e29c488ffd7c
Revises: 1f04d504d348
Create Date: 2021-04-11 01:45:22.128622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29c488ffd7c'
down_revision = '1f04d504d348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subcription_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_Products_subcription_type'), 'Products', ['subcription_type'], unique=False)
    op.create_table('Strategies',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=64), nullable=True),
    sa.Column('product_strategy_algorithm', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_Strategies_product_strategy_algorithm'), 'Strategies', ['product_strategy_algorithm'], unique=False)
    op.create_index(op.f('ix_Strategies_strategy_name'), 'Strategies', ['strategy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Strategies_strategy_name'), table_name='Strategies')
    op.drop_index(op.f('ix_Strategies_product_strategy_algorithm'), table_name='Strategies')
    op.drop_table('Strategies')
    op.drop_index(op.f('ix_Products_subcription_type'), table_name='Products')
    op.drop_table('Products')
    # ### end Alembic commands ###
